baseURL = "https://container-os.github.io/"
languageCode = "en-us"
title = "Easystack container linux opensource"
theme = "es-ananke"
publishDir = "public"
SectionPagesMenu = "main"
mainSections = ["posts"]
hasCJKLanguage = true

[params]
  favicon = ""
  github = "https://github.com/container-os/"
  env = "dev"
  background_color_class = "bg-navy"

[[menu.main]]
    name = "Projects"
    weight = 10
    identifier = "projects"
    url = "/projects/"

[[menu.main]]
    name = "About"
    weight = 20
    identifier = "about"
    url = "/about/"

[[menu.main]]
    name = "Contribute"
    weight = 30
    identifier = "contribute"
    url = "/contribute/"

[[menu.main]]
    name = "Contact"
    weight = 40
    identifier = "contact"
    url = "/contact/"
