#!/usr/bin/env python
import subprocess

projects = [
  {
     "title": "Container-OS specific kernel",
     "repo": "container-os/linux",
     "branch": "easystack",
     "file": "README",
     "target": "linux-kernel.md"
  },
  {
     "title": "Container-OS specific initramfs",
     "repo": "container-os/initramfs",
     "branch": "master",
     "file": "README.md",
     "target": "initramfs.md"
  },
  {
     "title": "Yak application keeper",
     "repo": "goyak/yak",
     "branch": "docs",
     "file": "_index.md",
     "target": "yak.md"
  },
]

for p in projects:
    url = "https://raw.githubusercontent.com/{repo}/{branch}/{file}".format(**p)
    target = "content/projects/{target}".format(**p)
    header = """---
title: {title}
ProjectURL: https://github.com/{repo}
---
""".format(**p)

    subprocess.call(['curl', url,'-o', target])

    with open(target, "r+") as f:
        s = f.read()
        if not (s[0:3] == "+++" or s[0:3] == "---"):
           f.seek(0)
           f.write(header+"\n"+s)
